"""Author the cafe as shared data, never renderer-specific geometry.

FRAMING, calculated before placement (square 1200 px, 50 mm, 24 mm sensor):
  view depth / full frame width and height (metres)
       0.9 / .432       1.5 / .720       2.0 / .960
       2.5 / 1.200      4.0 / 1.920      6.0 / 2.880
       9.0 / 4.320     12.0 / 5.760     15.0 / 7.200
Half extent = sensor/(2*lens)*depth = .24*depth, NOT .141*depth (85mm).
For downward pitch p and point (y, dz=5-z) relative to the eye at (0,0,5):
  D = dz*cos(p) - y*sin(p); V = dz*sin(p) + y*cos(p)
  NDC_y = V/(.24*D).
The 78 cm high hero table is .72 m below the eye, ends after .88 m,
and its near/far edges dz=1.99/2.87 project to NDC_y=-.88/-.45 at p=8deg.
Keeping its near edge above NDC_y=-1 requires p>6.4deg. Keeping the 1.6m
high back wall top (dz=15) visible requires p<7.4deg at its top edge; we
accept cropping the top 16cm at p=8deg, while the useful wall at y=1.2m
requires p<8.9deg. Thus 6.4..8.9deg is usable, and 8deg keeps useful wall.
The service counter is lateral and far away; it never becomes a near-eye
surface receding to the vanishing point.

Identical 110mm-high cups have 70mm base / 94.5mm top diameters. At D=2.5m
the top diameter spans 94.5 pixels; 64 segments give <.06 px radial sagitta.
At 1200px the 880mm hero table spans ~880px; 128 segments give <.14px
sagitta. Near leaves use 32 segments; distant furniture uses 24..48.
Cups and plant pots use ONE frustum each. Handles/rims are bent round stock,
not closed-cylinder stacks pretending to be a turned profile.

Round stock uses R=Ry*Rx*Rz. Set z=0: R*(0,1,0)=(sin(y)sin(x),cos(x),
cos(y)sin(x)). For unit direction d, x=acos(d.y), y=atan2(d.x,d.z).
The endpoints therefore map exactly to pos +/- length*d/2, including down.
All jitter is scalar brightness unless hue variation is explicitly requested.
No textures; all detail is actual mesh geometry. Units are metres.
"""

import argparse
import math
from pathlib import Path
import random

ROOT = Path(__file__).resolve().parents[2]
WOOD = (0.24, 0.105, 0.047)
DARK = (0.022, 0.029, 0.026)
CREAM = (0.72, 0.64, 0.48)
GREEN = (0.038, 0.14, 0.065)


class Builder:
    def __init__(self):
        self.lines = [
            "# Generated by tools/scene/build_cafe.py. Do not hand edit.",
            "version 1",
            "capture width 1200 height 1200",
            "camera pos 0 0 5 yaw -90 pitch -8 focus 2.5 fnumber 1.2 lens 50 sensor 24",
            "imported pos 0 -.75 0 rot -90 0 0 size .1 .1 .1 rgb .62 .44 .20",
            "sun dir -.82 .46 .20 color 1 .91 .78 energy 2.8 angle 0",
            "ambient color .80 .86 1 strength .22",
            "shadow lo -3.5 -1.6 -10.5 hi 3.5 1.8 5.5",
        ]
        self.rng = random.Random(20261002)

    def mark(self, text):
        self.lines.append("# " + text)

    def add(self, kind, pos, size, rgb, rot=(0, 0, 0), **kwargs):
        pairs = dict(pos=pos, size=size, rot=rot, rgb=rgb, **kwargs)
        self.lines.append(
            kind
            + " "
            + " ".join(
                k
                + " "
                + " ".join(
                    f"{v:.9g}" for v in (value if isinstance(value, (tuple, list)) else (value,))
                )
                for k, value in pairs.items()
            )
        )

    def box(self, pos, size, rgb, rot=(0, 0, 0), bevel=0):
        self.add("box", pos, size, rgb, rot, bevel=bevel)

    def cyl(self, pos, size, rgb, rot=(0, 0, 0), seg=48, taper=1, emit=0):
        self.add("cyl", pos, size, rgb, rot, seg=seg, taper=taper, emit=emit)

    def sph(self, pos, size, rgb, rot=(0, 0, 0), seg=24, emit=0):
        self.add("sph", pos, size, rgb, rot, seg=seg, emit=emit)

    def jitter(self, rgb, amount=0.10, hue=False):
        if hue:
            return tuple(c * self.rng.uniform(1 - amount, 1 + amount) for c in rgb)
        scale = self.rng.uniform(1 - amount, 1 + amount)
        return tuple(c * scale for c in rgb)

    def stock(self, a, b, diameter, rgb, seg=24, emit=0):
        d = tuple(b[k] - a[k] for k in range(3))
        length = math.sqrt(sum(v * v for v in d))
        if length < 1e-8:
            raise ValueError("zero length stock")
        rot = (
            math.degrees(math.acos(max(-1, min(1, d[1] / length)))),
            math.degrees(math.atan2(d[0], d[2])),
            0,
        )
        self.cyl(
            tuple((a[k] + b[k]) * 0.5 for k in range(3)),
            (diameter, length, diameter),
            rgb,
            rot,
            seg,
            emit=emit,
        )

    def curve(self, points, diameter, rgb, seg=16):
        for a, b in zip(points, points[1:]):
            self.stock(a, b, diameter, rgb, seg)

    def ring(self, x, y, z, radius, wire, rgb, segments=64):
        self.curve(
            [
                (
                    x + radius * math.cos(i * 2 * math.pi / segments),
                    y,
                    z + radius * math.sin(i * 2 * math.pi / segments),
                )
                for i in range(segments + 1)
            ],
            wire,
            rgb,
            12,
        )

    def cup(self, x, z, table_y=-0.72):
        # One frustum body. Coffee covers the cap inside a separate rolled rim.
        y = table_y + 0.008
        self.cyl((x, y - 0.004, z), (0.145, 0.008, 0.145), CREAM, seg=64)
        self.cyl((x, y + 0.055, z), (0.070, 0.110, 0.070), CREAM, seg=64, taper=1.35)
        self.cyl((x, y + 0.1108, z), (0.087, 0.0012, 0.087), (0.045, 0.017, 0.006), seg=64)
        self.ring(x, y + 0.111, z, 0.0455, 0.0035, CREAM)
        self.curve(
            [
                (x + 0.044 + 0.027 * math.cos(t), y + 0.060 + 0.039 * math.sin(t), z)
                for t in [(-math.pi * 0.64) + i * (1.28 * math.pi) / 48 for i in range(49)]
            ],
            0.009,
            CREAM,
            16,
        )

    def table(self, x, z, r=0.44):
        self.cyl((x, -0.741, z), (r * 2, 0.042, r * 2), WOOD, seg=128 if r == 0.44 else 80)
        self.cyl((x, -1.12, z), (0.065, 0.716, 0.065), DARK, seg=40)
        self.cyl((x, -1.485, z), (0.46, 0.03, 0.46), DARK, seg=64, taper=0.85)

    def chair(self, x, z, yaw=0):
        def world(p):
            t = math.radians(yaw)
            a, y, b = p
            return (x + a * math.cos(t) + b * math.sin(t), y, z - a * math.sin(t) + b * math.cos(t))

        self.box(world((0, -1.04, 0)), (0.39, 0.035, 0.38), WOOD, (0, yaw, 0), 0.012)
        for a in (-1, 1):
            for b in (-1, 1):
                self.stock(
                    world((a * 0.14, -1.058, b * 0.13)),
                    world((a * 0.19, -1.49, b * 0.18)),
                    0.024,
                    DARK,
                )
        for a in (-1, 1):
            self.stock(
                world((a * 0.17, -1.03, -0.15)), world((a * 0.17, -0.57, -0.18)), 0.022, DARK
            )
        points = [
            world((0.18 * math.cos(t), -0.63 + 0.055 * math.sin(t), -0.17 - 0.035 * math.sin(t)))
            for t in [i * math.pi / 32 for i in range(33)]
        ]
        self.curve(points, 0.045, WOOD)
        self.stock(world((-0.16, -0.76, -0.17)), world((0.16, -0.76, -0.17)), 0.035, WOOD)

    def plant(self, x, z, base=-1.5, scale=1):
        self.cyl(
            (x, base + 0.15 * scale, z),
            (0.22 * scale, 0.30 * scale, 0.22 * scale),
            (0.26, 0.095, 0.05),
            seg=64,
            taper=1.28,
        )
        self.cyl(
            (x, base + 0.301 * scale, z),
            (0.26 * scale, 0.002 * scale, 0.26 * scale),
            (0.022, 0.014, 0.008),
            seg=48,
        )
        for i in range(12):
            a = i * 2.399963
            h = (0.45 + 0.038 * i) * scale
            tip = (x + 0.18 * scale * math.cos(a), base + h, z + 0.18 * scale * math.sin(a))
            self.stock((x, base + 0.27 * scale, z), tip, 0.006 * scale, GREEN, 12)
            # Curved ellipsoidal blades have thickness and smoothly varying normals.
            self.sph(
                tip,
                (0.105 * scale, 0.30 * scale, 0.024 * scale),
                self.jitter(GREEN, 0.16, True),
                (25, math.degrees(-a), -28 + 4 * i),
                seg=32,
            )


def build():
    b = Builder()
    b.mark(
        "Room: floor -1.5m, ceiling +1.6m. Left glazing is an OPEN aperture, never emissive opaque panes."
    )
    b.box((0, -1.545, -2.5), (6.2, 0.09, 15.2), (0.17, 0.13, 0.095))
    for row in range(30):
        z = 4.75 - row * 0.50
        for col in range(8):
            x = -2.625 + col * 0.75
            b.box(
                (x, -1.496, z),
                (0.745, 0.008, 0.495),
                b.jitter((0.28, 0.22, 0.15), 0.065),
                bevel=0.001,
            )
    b.box((0, 1.65, -2.5), (6.2, 0.1, 15.2), (0.66, 0.65, 0.59))
    b.box((3.06, 0.05, -2.5), (0.12, 3.1, 15.2), (0.39, 0.44, 0.37))
    b.box((0, 0.05, -10.06), (6.2, 3.1, 0.12), (0.52, 0.47, 0.37))
    # Window opening: y=-.9..1.45, z=-9..4.4. Sun travels through it toward +X.
    b.box((-3.06, -1.2, -2.5), (0.12, 0.60, 15.2), (0.55, 0.51, 0.43))
    b.box((-3.06, 1.55, -2.5), (0.12, 0.1, 15.2), (0.55, 0.51, 0.43))
    for z in (4.5, 1.8, -0.9, -3.6, -6.3, -9.0):
        b.box((-3, 0.25, z), (0.08, 2.40, 0.045), DARK, bevel=0.006)
    b.box((-3, -0.91, -2.25), (0.17, 0.055, 13.5), WOOD, bevel=0.008)
    b.mark("Hero and repeated IDENTICAL cups; listed distances are view-axis depths to cup centre.")
    # y=.72 below eye + saucer .008 + half cup .055 = -.657.
    for d, x in ((2.5, 0), (4, -0.48), (6, 0.65), (9, -1.0), (12, 0.50)):
        z = 5 - (d - 0.657 * math.sin(math.radians(8))) / math.cos(math.radians(8))
        b.mark(f"Repeated cup: depth {d} m, x {x} m")
        b.table(x, z)
        b.cup(x, z)
        b.chair(x - 0.62, z - 0.05, 90)
        if d > 3:
            b.chair(x + 0.62, z + 0.08, -90)
        # A small real candle: emitter radiance peak 15, repeated at cup depths.
        b.cyl(
            (x + 0.20, -0.69, z - 0.11),
            (0.047, 0.06, 0.047),
            (0.38, 0.22, 0.08),
            seg=48,
            taper=0.92,
        )
        b.sph((x + 0.20, -0.647, z - 0.11), (0.009, 0.023, 0.009), (1, 0.56, 0.18), seg=24, emit=15)
    b.mark("Foreground foliage at 1.2m; pot sits on its own low table, outside hero table.")
    b.box((-0.30, -0.92, 3.7), (0.40, 0.045, 0.42), WOOD, bevel=0.010)
    for x in (-0.44, -0.16):
        for z in (3.56, 3.84):
            b.stock((x, -0.943, z), (x, -1.50, z), 0.023, DARK)
    b.plant(-0.30, 3.7, base=-0.8975, scale=0.62)
    b.plant(-2.50, -8.9, scale=1.3)
    b.mark("Lateral service counter, far enough away not to dominate the camera.")
    b.box((2.36, -0.98, -5.0), (1.15, 1.04, 7.6), (0.14, 0.075, 0.042), bevel=0.015)
    b.box((2.34, -0.425, -5.0), (1.30, 0.07, 7.7), (0.48, 0.44, 0.35), bevel=0.015)
    for z in [-1.45 - i * 0.17 for i in range(43)]:
        b.box((1.777, -0.99, z), (0.018, 0.95, 0.075), b.jitter(WOOD, 0.07), bevel=0.005)
    b.mark("Espresso machine: supported feet, body and drip tray, no luminous panels.")
    for x in (2.05, 2.62):
        for z in (-7.35, -6.87):
            b.cyl((x, -0.366, z), (0.044, 0.048, 0.044), DARK, seg=32)
    b.box((2.335, -0.12, -7.16), (0.68, 0.445, 0.54), (0.28, 0.30, 0.27), bevel=0.045)
    b.box((2.335, -0.035, -6.868), (0.60, 0.23, 0.045), (0.028, 0.033, 0.029), bevel=0.012)
    b.box((2.335, -0.340, -6.74), (0.68, 0.04, 0.31), (0.23, 0.25, 0.22), bevel=0.009)
    for x in (2.19, 2.47):
        b.cyl((x, -0.14, -6.80), (0.07, 0.10, 0.07), (0.28, 0.29, 0.27), seg=32)
        b.stock((x, -0.16, -6.79), (x, -0.16, -6.62), 0.025, DARK)
        b.cyl((x, -0.305, -6.74), (0.047, 0.030, 0.047), CREAM, seg=32, taper=1.15)
    for x in (2.08, 2.59):
        b.cyl((x, 0.02, -6.836), (0.046, 0.012, 0.046), (0.68, 0.67, 0.56), (90, 0, 0), seg=32)
    # Grinder to the side: tapered single hopper, never a ring-stack dome.
    b.box((2.36, -0.29, -5.96), (0.22, 0.20, 0.25), DARK, bevel=0.025)
    b.cyl((2.36, -0.09, -5.98), (0.17, 0.20, 0.17), (0.12, 0.075, 0.028), seg=64, taper=1.40)
    b.cyl((2.36, 0.014, -5.98), (0.25, 0.008, 0.25), DARK, seg=64)
    b.mark("Back shelving, ceramic canisters and warm pin lights, all at measurable depths.")
    for y in (-0.25, 0.30, 0.85):
        b.box((0.8, y, -9.77), (3.6, 0.035, 0.40), WOOD, bevel=0.008)
        for i in range(9):
            x = -0.75 + i * 0.36
            b.cyl(
                (x, y + 0.11, -9.75),
                (0.12, 0.185, 0.12),
                b.jitter((0.32, 0.27, 0.16), 0.15),
                seg=32,
                taper=0.92,
            )
    # Brushed rails with bulbs at multiple depths, not an emissive wall.
    for z in (2.4, 0.5, -2, -4.5, -7, -9.3):
        for x in (-1.65, 1.2):
            b.stock((x, 1.59, z), (x, 0.55, z), 0.008, DARK, 12)
            b.cyl((x, 0.485, z), (0.20, 0.13, 0.20), (0.17, 0.105, 0.05), seg=64, taper=0.4)
            b.sph((x, 0.405, z), (0.046, 0.038, 0.046), (1, 0.72, 0.40), seg=32, emit=9)
    # Small bulbs form out-of-focus discs even where the near pendants are cropped.
    for i, z in enumerate((3.1, 2.45, 1.0, -0.5, -2.2, -4.2, -6.5, -9.2)):
        x = (-1 if i % 2 else 1) * (0.12 + 0.13 * (5 - z))
        b.sph((x, -0.12, z), (0.010, 0.010, 0.010), (1, 0.67, 0.30), seg=24, emit=20)
        b.stock((x, 1.59, z), (x, -0.10, z), 0.003, DARK, 12)
    return "\n".join(b.lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "scene/cafe.scene")
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build())
    print(args.output)


if __name__ == "__main__":
    main()
